tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "puma/puma"

brew "openssl"
brew "autoconf"
brew "autoconf-archive"
brew "automake"
brew "gdbm"
brew "openssl@1.1"
brew "sqlite"
brew "python"
brew "awscli"
brew "bash-completion"
brew "bison"
brew "chruby"
brew "coreutils"
brew "curl"
brew "docker", link: false
brew "docker-clean"
brew "docker-completion"
brew "dos2unix"
brew "libtool"
brew "git"
brew "git-lfs"
brew "libffi"
brew "graphicsmagick"
brew "grip"
brew "imagemagick"
brew "jmeter"
brew "libxml2"
brew "libyaml"
brew "llvm"
brew "md5sha1sum", link: false
brew "pkg-config"
brew "readline"
brew "rustup-init"
brew "screen"
brew "spark"
brew "tmux"
brew "unzip"
brew "watch"
brew "watchman"
brew "wget"
brew "zsh"
brew "zsh-completions"

unless ENV['HOMEBREW_SYSTEM'] == 'Linux'
  brew "gcc"
  brew "mas"
  brew "putty"

  cask "font-fira-code"
  cask "font-hack-nerd-font"
  cask "meld"
  cask "ngrok"
  cask "postman"
  cask "spectacle"
  cask "visual-studio-code"
  cask "visual-studio-code-insiders"
  mas "Slack", id: 803453959
  # mas "Wunderlist", id: 410628904
end
