# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: /app
    docker:
       - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build --tag=dotfiles .
      - run:
          name: Run image
          command: |
            docker run dotfiles which zsh