# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: /app
    docker:
       - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build base image
          command: |
            DOCKER_USER=christraeger docker build --tag=dotfiles.base docker/base
      - run:
          name: Build image
          command: |
            docker build --tag=dotfiles -f docker/prod/Dockerfile .
      - run:
          name: Run image
          command: |
            docker run dotfiles which zsh
            docker run dotfiles zsh -c 'source ~/.zshrc && which ws'
      - run:
          name: Push to Docker Hub
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS

              docker tag dotfiles adriancarriger/dotfiles:latest
              docker push adriancarriger/dotfiles:latest

              docker tag dotfiles "adriancarriger/dotfiles:${CIRCLE_BUILD_NUM}"
              docker push "adriancarriger/dotfiles:${CIRCLE_BUILD_NUM}"
            fi
